require("ana")

--vim.diagnostic.config({
--	-- Grammarly default is to show the issue at the end
--	-- of the line (virtual text), I prefer it in a float,
--	-- so turn off the virtual text
--	virtual_text = false,
--	update_in_insert = true,
--	underline = true,
--	severity_sort = true,
--	float = {
--		focusable = false,
--		style = "minimal",
--		border = "rounded",
--
--		-- show the name of the LSP
--		source = "always",
--
--		-- set header to nothing to avoid
--		-- a line reading "Diagnostics:"
--		header = "",
--
--		-- Set prefix to nothing to avoid
--		-- numbering multiple errors on a
--		-- phrase
--		prefix = "",
--	},
--})
